// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQvR0PF3I4MoAFlr30AyMzlkjO5J1L2L8',
    appId: '1:854600484014:web:6ad0666f54daa74efed93f',
    messagingSenderId: '854600484014',
    projectId: 'kb-finance-app',
    authDomain: 'kb-finance-app.firebaseapp.com',
    databaseURL: 'https://kb-finance-app-default-rtdb.firebaseio.com',
    storageBucket: 'kb-finance-app.appspot.com',
    measurementId: 'G-FWV5VDFXLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHfzm72_vlKAgC-RcVTgerZDF1MkSqcc',
    appId: '1:854600484014:android:b46248d71cdf5595fed93f',
    messagingSenderId: '854600484014',
    projectId: 'kb-finance-app',
    databaseURL: 'https://kb-finance-app-default-rtdb.firebaseio.com',
    storageBucket: 'kb-finance-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHfzm72_vlKAgC-RcVTgerZDF1MkSqcc',
    appId: '1:854600484014:android:b46248d71cdf5595fed93f',
    messagingSenderId: '854600484014',
    projectId: 'kb-finance-app',
    databaseURL: 'https://kb-finance-app-default-rtdb.firebaseio.com',
    storageBucket: 'kb-finance-app.appspot.com',
    iosBundleId: 'com.demo.creditapp',
  );
}
